const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
const ok=data=>json({ok:true,data});
const fail=(error,status=400,code="REQUEST_FAILED",details=null)=>json({ok:false,error:String(error||"Grading Copilot request failed."),code,...(details?{details}:{})},status);
class CanvasRequestError extends Error{constructor(message,{status=502,code="CANVAS_REQUEST_FAILED",endpoint="",canvasMessage=""}={}){super(message);this.name="CanvasRequestError";this.status=status;this.code=code;this.endpoint=endpoint;this.canvasMessage=canvasMessage;}}
function canvasConfig(env){const raw=String(env.CANVAS_BASE_URL||"").trim();if(!raw)throw new Error("Canvas URL is not configured.");const u=new URL(raw);if(u.protocol!=="https:")throw new Error("Canvas URL must use HTTPS.");const allowed=new Set([u.hostname.toLowerCase()]);const host=u.hostname.toLowerCase();if(!allowed.has(host))throw new Error("Canvas host is not approved.");const token=String(env.CANVAS_ACCESS_TOKEN||"").trim();if(!token)throw new Error("Grading Copilot Canvas credentials are not configured.");return{base:u.origin,host,token};}
function canvasHeaders(token,extra={}){return{Authorization:`Bearer ${token}`,Accept:"application/json",...extra};}
function canvasMessage(body){return String(body?.errors?.[0]?.message||body?.message||body?.error||"").trim();}
async function requestJson(url,init={}){const response=await fetch(url,init);const text=await response.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={raw:text};}if(!response.ok){const endpoint=new URL(url).pathname,remote=canvasMessage(body);if(response.status===401)throw new CanvasRequestError("Canvas rejected the configured access token.",{status:401,code:"CANVAS_TOKEN_REJECTED",endpoint,canvasMessage:remote});if(response.status===403)throw new CanvasRequestError("Canvas denied access to this resource.",{status:403,code:"CANVAS_ACCESS_DENIED",endpoint,canvasMessage:remote});if(response.status===404)throw new CanvasRequestError("Canvas could not find this resource.",{status:404,code:"CANVAS_RESOURCE_NOT_FOUND",endpoint,canvasMessage:remote});throw new CanvasRequestError(remote||`Canvas request failed (${response.status}).`,{status:response.status,endpoint,canvasMessage:remote});}return{body,response};}
async function paged(url,token){const all=[];let next=url;for(let page=0;next&&page<30;page++){const {body,response}=await requestJson(next,{headers:canvasHeaders(token)});if(!Array.isArray(body))throw new Error("Canvas returned an unexpected list response.");all.push(...body);const link=response.headers.get("link")||"",m=link.match(/<([^>]+)>;\s*rel="next"/);next=m?m[1]:"";}return all;}
const enc=v=>encodeURIComponent(String(v));
async function handle(payload,env){const c=canvasConfig(env),action=String(payload?.action||"status");
 if(action==="status")return{service:"Grading Copilot",status:"available",canvasConfigured:true,canvasHost:c.host,writesEnabled:env.GRADING_COPILOT_WRITE_ENABLED==="true"};
 if(action==="verifyIdentity"){const {body}=await requestJson(`${c.base}/api/v1/users/self/profile`,{headers:canvasHeaders(c.token)});return{authenticated:true,userId:String(body.id||""),displayName:String(body.name||body.short_name||"").trim(),canvasHost:c.host};}
 if(action==="verifyCourse"){const courseId=String(payload.courseId||"").trim();if(!courseId)throw new Error("courseId is required.");const {body}=await requestJson(`${c.base}/api/v1/courses/${enc(courseId)}`,{headers:canvasHeaders(c.token)});return{courseId:String(body.id||courseId),courseName:String(body.name||body.course_code||"").trim(),courseCode:String(body.course_code||""),canvasHost:c.host,courseUrl:body.html_url||`${c.base}/courses/${enc(courseId)}`,diagnostic:"course access verified directly"};}
 if(action==="listAssignments"){if(!payload.courseId)throw new Error("courseId is required.");return paged(`${c.base}/api/v1/courses/${enc(payload.courseId)}/assignments?per_page=100&order_by=due_at`,c.token);}
 if(action==="listSubmissions"){if(!payload.courseId||!payload.assignmentId)throw new Error("courseId and assignmentId are required.");return paged(`${c.base}/api/v1/courses/${enc(payload.courseId)}/assignments/${enc(payload.assignmentId)}/submissions?include[]=user&include[]=submission_comments&per_page=100`,c.token);}
 if(action==="postGrade"){if(env.GRADING_COPILOT_WRITE_ENABLED!=="true")throw Object.assign(new Error("Canvas grade writes are disabled."),{status:403,code:"WRITES_DISABLED"});if(payload.confirmWrite!==true)throw Object.assign(new Error("Explicit confirmWrite=true is required."),{status:400,code:"CONFIRMATION_REQUIRED"});for(const k of ["courseId","assignmentId","userId","grade","feedback"])if(payload[k]===undefined||payload[k]===null||payload[k]==="")throw new Error(`${k} is required.`);const body=new URLSearchParams();body.set("submission[posted_grade]",String(payload.grade));body.set("comment[text_comment]",String(payload.feedback));await requestJson(`${c.base}/api/v1/courses/${enc(payload.courseId)}/assignments/${enc(payload.assignmentId)}/submissions/${enc(payload.userId)}`,{method:"PUT",headers:canvasHeaders(c.token,{"content-type":"application/x-www-form-urlencoded;charset=UTF-8"}),body:body.toString()});const {body:verified}=await requestJson(`${c.base}/api/v1/courses/${enc(payload.courseId)}/assignments/${enc(payload.assignmentId)}/submissions/${enc(payload.userId)}?include[]=submission_comments`,{headers:canvasHeaders(c.token)});return{verified:true,verification:"fresh Canvas read after write",submission:verified};}
 throw Object.assign(new Error(`Unsupported Grading Copilot action: ${action}`),{status:404,code:"UNSUPPORTED_ACTION"});
}
export async function onRequestGet(context){try{return ok(await handle({action:"status"},context.env));}catch(error){return fail(error?.message||error,error?.status||500,error?.code||"GRADING_COPILOT_ERROR");}}
export async function onRequestPost(context){try{return ok(await handle(await context.request.json(),context.env));}catch(error){if(error instanceof CanvasRequestError)return fail(error.message,error.status,error.code,{endpoint:error.endpoint,canvasMessage:error.canvasMessage||null});return fail(error?.message||error,error?.status||500,error?.code||"GRADING_COPILOT_ERROR");}}
